//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bank_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class account
    {
        public int accountID { get; set; }
        public string account_number { get; set; }
        public double amount { get; set; }
        public int CustomerID { get; set; }
    
        public virtual Openingaccount Openingaccount { get; set; }
    }
}
